databases:
  - name: ctfd-db
    plan: free
    databaseName: ctfd
    user: ctfd

services:
  - name: ctfd
    type: web
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ctfd-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: ctfd-redis
          type: redis
          property: connectionString
      - key: UPLOAD_FOLDER
        value: /var/uploads
      - key: LOG_FOLDER
        value: /var/log/CTFd
      - key: REVERSE_PROXY
        value: "true"
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: ctfd-data
      mountPath: /var/uploads
      sizeGB: 1

  - name: ctfd-redis
    type: redis
    plan: free
    ipAllowList: []

